var aData = {
    details:[
        {
            img:1,
            bank:"浦发银行",
            rate:5.5,
            mortgageSituation:false,
            loan:60
        },
        {
            img:2,
            bank:"光大银行",
            rate:5.6,
            mortgageSituation:true,
            loan:80
        },
        {
            img:3,
            bank:"招商银行",
            rate:5.8,
            mortgageSituation:false,
            loan:90
        }
    ]
}